// This file was generated once from the extracted Herdr data and is maintained
// by hand; keep it in sync with Herdr when porting a new Herdr release.
//
// The 18 Herdr palettes below are derived from Herdr v0.9.3 src/app/state.rs
// (https://github.com/herdrdev/herdr), Copyright the Herdr authors, licensed
// under the Apache License, Version 2.0
// (http://www.apache.org/licenses/LICENSE-2.0). The values are copied
// unchanged, token for token and in the field order of Herdr's Palette
// struct, so that the "inherit" theme reproduces Herdr's colors exactly. The
// per-theme comments are Herdr's own doc comments. See THIRD_PARTY_NOTICES.md
// at the repository root.
//
// catppuccin-frappe and catppuccin-macchiato are not Herdr themes: they apply
// the token mapping Herdr uses for Catppuccin Mocha (accent=blue,
// panel_bg=mantle, sidebar_bg=reset, active_row_bg=base, selection_bg=surface0,
// surface_dim=base, the rest by name) to the official Catppuccin Frappé and
// Macchiato colors (https://github.com/catppuccin/palette, MIT).

package theme

// builtinSpecs lists the built-in palettes in Herdr's THEME_NAMES order,
// followed by shep's two extra Catppuccin flavors. Every entry sets all 19
// tokens using Herdr's color syntax and is parsed into builtinPalettes at
// package initialization.
var builtinSpecs = []builtinSpec{
	{
		// Catppuccin Mocha — the default.
		name: "catppuccin",
		colors: [numTokens]string{
			TokenAccent:      "#89b4fa",
			TokenPanelBg:     "#181825",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#1e1e2e",
			TokenSelectionBg: "#313244",
			TokenSurface0:    "#313244",
			TokenSurface1:    "#45475a",
			TokenSurfaceDim:  "#1e1e2e",
			TokenOverlay0:    "#6c7086",
			TokenOverlay1:    "#7f849c",
			TokenText:        "#cdd6f4",
			TokenSubtext0:    "#a6adc8",
			TokenMauve:       "#cba6f7",
			TokenGreen:       "#a6e3a1",
			TokenYellow:      "#f9e2af",
			TokenRed:         "#f38ba8",
			TokenBlue:        "#89b4fa",
			TokenTeal:        "#94e2d5",
			TokenPeach:       "#fab387",
		},
	},
	{
		// Catppuccin Latte — the light Catppuccin flavor.
		name: "catppuccin-latte",
		colors: [numTokens]string{
			TokenAccent:      "#1e66f5",
			TokenPanelBg:     "#eff1f5",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#e6e9ef",
			TokenSelectionBg: "#bdd0f5",
			TokenSurface0:    "#ccd0da",
			TokenSurface1:    "#bcc0cc",
			TokenSurfaceDim:  "#e6e9ef",
			TokenOverlay0:    "#9ca0b0",
			TokenOverlay1:    "#8c8fa1",
			TokenText:        "#4c4f69",
			TokenSubtext0:    "#6c6f85",
			TokenMauve:       "#8839ef",
			TokenGreen:       "#40a02b",
			TokenYellow:      "#df8e1d",
			TokenRed:         "#d20f39",
			TokenBlue:        "#1e66f5",
			TokenTeal:        "#179299",
			TokenPeach:       "#fe640b",
		},
	},
	{
		// Terminal 16-color theme.
		name: "terminal",
		colors: [numTokens]string{
			TokenAccent:      "blue",
			TokenPanelBg:     "reset",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "darkgray",
			TokenSelectionBg: "reset",
			TokenSurface0:    "reset",
			TokenSurface1:    "darkgray",
			TokenSurfaceDim:  "darkgray",
			TokenOverlay0:    "gray",
			TokenOverlay1:    "white",
			TokenText:        "reset",
			TokenSubtext0:    "gray",
			TokenMauve:       "gray",
			TokenGreen:       "green",
			TokenYellow:      "yellow",
			TokenRed:         "lightred",
			TokenBlue:        "blue",
			TokenTeal:        "cyan",
			TokenPeach:       "yellow",
		},
	},
	{
		// Tokyo Night — blue-purple aesthetic.
		name: "tokyo-night",
		colors: [numTokens]string{
			TokenAccent:      "#7aa2f7",
			TokenPanelBg:     "#1a1b26",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#232636",
			TokenSelectionBg: "#2d3650",
			TokenSurface0:    "#24283b",
			TokenSurface1:    "#414868",
			TokenSurfaceDim:  "#1a1b26",
			TokenOverlay0:    "#565f89",
			TokenOverlay1:    "#697196",
			TokenText:        "#c0caf5",
			TokenSubtext0:    "#a9b1d6",
			TokenMauve:       "#bb9af7",
			TokenGreen:       "#9ece6a",
			TokenYellow:      "#e0af68",
			TokenRed:         "#f7768e",
			TokenBlue:        "#7aa2f7",
			TokenTeal:        "#7dcfff",
			TokenPeach:       "#ff9e64",
		},
	},
	{
		// Tokyo Night Day — the light Tokyo Night style.
		name: "tokyo-night-day",
		colors: [numTokens]string{
			TokenAccent:      "#2e7de9",
			TokenPanelBg:     "#e1e2e7",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#d2d3da",
			TokenSelectionBg: "#b6cae7",
			TokenSurface0:    "#c4c8da",
			TokenSurface1:    "#a8aecb",
			TokenSurfaceDim:  "#d2d3da",
			TokenOverlay0:    "#8990b3",
			TokenOverlay1:    "#68709a",
			TokenText:        "#3760bf",
			TokenSubtext0:    "#6172b0",
			TokenMauve:       "#7847bd",
			TokenGreen:       "#587539",
			TokenYellow:      "#8c6c3e",
			TokenRed:         "#f52a65",
			TokenBlue:        "#2e7de9",
			TokenTeal:        "#118c74",
			TokenPeach:       "#b15c00",
		},
	},
	{
		// Dracula — purple/pink/green.
		name: "dracula",
		colors: [numTokens]string{
			TokenAccent:      "#bd93f9",
			TokenPanelBg:     "#282a36",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#373c52",
			TokenSelectionBg: "#463f5d",
			TokenSurface0:    "#44475a",
			TokenSurface1:    "#6272a4",
			TokenSurfaceDim:  "#282a36",
			TokenOverlay0:    "#6272a4",
			TokenOverlay1:    "#828cb4",
			TokenText:        "#f8f8f2",
			TokenSubtext0:    "#d2d2dc",
			TokenMauve:       "#ff79c6",
			TokenGreen:       "#50fa7b",
			TokenYellow:      "#f1fa8c",
			TokenRed:         "#ff5555",
			TokenBlue:        "#8be9fd",
			TokenTeal:        "#8be9fd",
			TokenPeach:       "#ffb86c",
		},
	},
	{
		// Nord — frosty blue palette.
		name: "nord",
		colors: [numTokens]string{
			TokenAccent:      "#88c0d0",
			TokenPanelBg:     "#2e3440",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#434c5e",
			TokenSelectionBg: "#40505d",
			TokenSurface0:    "#3b4252",
			TokenSurface1:    "#434c5e",
			TokenSurfaceDim:  "#2e3440",
			TokenOverlay0:    "#4c566a",
			TokenOverlay1:    "#646e82",
			TokenText:        "#eceff4",
			TokenSubtext0:    "#d8dee9",
			TokenMauve:       "#b48ead",
			TokenGreen:       "#a3be8c",
			TokenYellow:      "#ebcb8b",
			TokenRed:         "#bf616a",
			TokenBlue:        "#81a1c1",
			TokenTeal:        "#8fbcbb",
			TokenPeach:       "#d08770",
		},
	},
	{
		// Gruvbox Dark — warm retro palette.
		name: "gruvbox",
		colors: [numTokens]string{
			TokenAccent:      "#d79921",
			TokenPanelBg:     "#282828",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#323130",
			TokenSelectionBg: "#4b3f27",
			TokenSurface0:    "#3c3836",
			TokenSurface1:    "#504945",
			TokenSurfaceDim:  "#282828",
			TokenOverlay0:    "#928374",
			TokenOverlay1:    "#a89984",
			TokenText:        "#ebdbb2",
			TokenSubtext0:    "#d5c4a1",
			TokenMauve:       "#d3869b",
			TokenGreen:       "#b8bb26",
			TokenYellow:      "#fabd2f",
			TokenRed:         "#fb4934",
			TokenBlue:        "#83a598",
			TokenTeal:        "#8ec07c",
			TokenPeach:       "#fe8019",
		},
	},
	{
		// Gruvbox Light — the light retro palette.
		name: "gruvbox-light",
		colors: [numTokens]string{
			TokenAccent:      "#076678",
			TokenPanelBg:     "#fbf1c7",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#f2e5bc",
			TokenSelectionBg: "#ebdbb2",
			TokenSurface0:    "#ebdbb2",
			TokenSurface1:    "#d5c4a1",
			TokenSurfaceDim:  "#f2e5bc",
			TokenOverlay0:    "#928374",
			TokenOverlay1:    "#7c6f64",
			TokenText:        "#3c3836",
			TokenSubtext0:    "#504945",
			TokenMauve:       "#8f3f71",
			TokenGreen:       "#79740e",
			TokenYellow:      "#b57614",
			TokenRed:         "#9d0006",
			TokenBlue:        "#076678",
			TokenTeal:        "#427b58",
			TokenPeach:       "#af3a03",
		},
	},
	{
		// One Dark — Atom's classic dark theme.
		name: "one-dark",
		colors: [numTokens]string{
			TokenAccent:      "#61afef",
			TokenPanelBg:     "#282c34",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#313640",
			TokenSelectionBg: "#334659",
			TokenSurface0:    "#2c313a",
			TokenSurface1:    "#3e4451",
			TokenSurfaceDim:  "#282c34",
			TokenOverlay0:    "#5c6370",
			TokenOverlay1:    "#737a87",
			TokenText:        "#abb2bf",
			TokenSubtext0:    "#969ca8",
			TokenMauve:       "#c678dd",
			TokenGreen:       "#98c379",
			TokenYellow:      "#e5c07b",
			TokenRed:         "#e06c75",
			TokenBlue:        "#61afef",
			TokenTeal:        "#56b6c2",
			TokenPeach:       "#d19a66",
		},
	},
	{
		// One Light — Atom's classic light theme.
		name: "one-light",
		colors: [numTokens]string{
			TokenAccent:      "#4078f2",
			TokenPanelBg:     "#fafafa",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#d8dbe2",
			TokenSelectionBg: "#cddbf8",
			TokenSurface0:    "#f0f0f1",
			TokenSurface1:    "#e5e5e6",
			TokenSurfaceDim:  "#f5f5f6",
			TokenOverlay0:    "#a0a1a7",
			TokenOverlay1:    "#686b77",
			TokenText:        "#383a42",
			TokenSubtext0:    "#686b77",
			TokenMauve:       "#a626a4",
			TokenGreen:       "#50a14f",
			TokenYellow:      "#c18401",
			TokenRed:         "#e45649",
			TokenBlue:        "#4078f2",
			TokenTeal:        "#0184bc",
			TokenPeach:       "#986801",
		},
	},
	{
		// Solarized Dark — Ethan Schoonover's classic.
		name: "solarized",
		colors: [numTokens]string{
			TokenAccent:      "#268bd2",
			TokenPanelBg:     "#002b36",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#164b57",
			TokenSelectionBg: "#083e55",
			TokenSurface0:    "#073642",
			TokenSurface1:    "#586e75",
			TokenSurfaceDim:  "#002b36",
			TokenOverlay0:    "#586e75",
			TokenOverlay1:    "#657b83",
			TokenText:        "#93a1a1",
			TokenSubtext0:    "#839496",
			TokenMauve:       "#d33682",
			TokenGreen:       "#859900",
			TokenYellow:      "#b58900",
			TokenRed:         "#dc322f",
			TokenBlue:        "#268bd2",
			TokenTeal:        "#2aa198",
			TokenPeach:       "#cb4b16",
		},
	},
	{
		// Solarized Light — Ethan Schoonover's light variant.
		name: "solarized-light",
		colors: [numTokens]string{
			TokenAccent:      "#268bd2",
			TokenPanelBg:     "#fdf6e3",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#eee8d5",
			TokenSelectionBg: "#c9dcdf",
			TokenSurface0:    "#eee8d5",
			TokenSurface1:    "#93a1a1",
			TokenSurfaceDim:  "#eee8d5",
			TokenOverlay0:    "#93a1a1",
			TokenOverlay1:    "#586e75",
			TokenText:        "#657b83",
			TokenSubtext0:    "#839496",
			TokenMauve:       "#d33682",
			TokenGreen:       "#859900",
			TokenYellow:      "#b58900",
			TokenRed:         "#dc322f",
			TokenBlue:        "#268bd2",
			TokenTeal:        "#2aa198",
			TokenPeach:       "#cb4b16",
		},
	},
	{
		// Kanagawa — inspired by Katsushika Hokusai.
		name: "kanagawa",
		colors: [numTokens]string{
			TokenAccent:      "#7e9cd8",
			TokenPanelBg:     "#1f1f28",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#363646",
			TokenSelectionBg: "#32384b",
			TokenSurface0:    "#2a2a37",
			TokenSurface1:    "#363646",
			TokenSurfaceDim:  "#1f1f28",
			TokenOverlay0:    "#727169",
			TokenOverlay1:    "#87867d",
			TokenText:        "#dcd7ba",
			TokenSubtext0:    "#c8c3aa",
			TokenMauve:       "#957fb8",
			TokenGreen:       "#76946a",
			TokenYellow:      "#c0a36e",
			TokenRed:         "#c34043",
			TokenBlue:        "#7e9cd8",
			TokenTeal:        "#7fb4ca",
			TokenPeach:       "#ffa066",
		},
	},
	{
		// Kanagawa Lotus — the light Kanagawa variant.
		name: "kanagawa-lotus",
		colors: [numTokens]string{
			TokenAccent:      "#4d699b",
			TokenPanelBg:     "#f2ecbc",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#d5cea3",
			TokenSelectionBg: "#dcd5ac",
			TokenSurface0:    "#dcd5ac",
			TokenSurface1:    "#c9cbd1",
			TokenSurfaceDim:  "#d5cea3",
			TokenOverlay0:    "#a09cac",
			TokenOverlay1:    "#8a8980",
			TokenText:        "#545464",
			TokenSubtext0:    "#43436c",
			TokenMauve:       "#624c83",
			TokenGreen:       "#6f894e",
			TokenYellow:      "#77713f",
			TokenRed:         "#c84053",
			TokenBlue:        "#4d699b",
			TokenTeal:        "#4e8ca2",
			TokenPeach:       "#cc6d00",
		},
	},
	{
		// Rosé Pine — muted, elegant.
		name: "rose-pine",
		colors: [numTokens]string{
			TokenAccent:      "#c4a7e7",
			TokenPanelBg:     "#191724",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#26233a",
			TokenSelectionBg: "#3b344b",
			TokenSurface0:    "#1f1d2e",
			TokenSurface1:    "#26233a",
			TokenSurfaceDim:  "#26233a",
			TokenOverlay0:    "#6e6a86",
			TokenOverlay1:    "#908caa",
			TokenText:        "#e0def4",
			TokenSubtext0:    "#c8c5dc",
			TokenMauve:       "#c4a7e7",
			TokenGreen:       "#31748f",
			TokenYellow:      "#f6c177",
			TokenRed:         "#eb6f92",
			TokenBlue:        "#31748f",
			TokenTeal:        "#9ccfd8",
			TokenPeach:       "#ea9a97",
		},
	},
	{
		// Rosé Pine Dawn — the light Rosé Pine variant.
		name: "rose-pine-dawn",
		colors: [numTokens]string{
			TokenAccent:      "#907aa9",
			TokenPanelBg:     "#faf4ed",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#e3d9cf",
			TokenSelectionBg: "#f2e9e1",
			TokenSurface0:    "#f2e9e1",
			TokenSurface1:    "#fffaf3",
			TokenSurfaceDim:  "#f2e9e1",
			TokenOverlay0:    "#9893a5",
			TokenOverlay1:    "#797593",
			TokenText:        "#464261",
			TokenSubtext0:    "#797593",
			TokenMauve:       "#907aa9",
			TokenGreen:       "#286983",
			TokenYellow:      "#ea9d34",
			TokenRed:         "#b4637a",
			TokenBlue:        "#286983",
			TokenTeal:        "#56949f",
			TokenPeach:       "#d7827e",
		},
	},
	{
		// Vesper — minimal high-contrast monochrome with peach and mint accents.
		name: "vesper",
		colors: [numTokens]string{
			TokenAccent:      "#ffc799",
			TokenPanelBg:     "#1a1a1a",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#101010",
			TokenSelectionBg: "#232323",
			TokenSurface0:    "#232323",
			TokenSurface1:    "#282828",
			TokenSurfaceDim:  "#101010",
			TokenOverlay0:    "#5c5c5c",
			TokenOverlay1:    "#7e7e7e",
			TokenText:        "#ffffff",
			TokenSubtext0:    "#a0a0a0",
			TokenMauve:       "#ffd1a8",
			TokenGreen:       "#99ffe4",
			TokenYellow:      "#ffc799",
			TokenRed:         "#ff8080",
			TokenBlue:        "#b0b0b0",
			TokenTeal:        "#66ddcc",
			TokenPeach:       "#ffc799",
		},
	},
	{
		// Catppuccin Frappé, mapped like Herdr's Catppuccin Mocha (shep addition).
		name: "catppuccin-frappe",
		colors: [numTokens]string{
			TokenAccent:      "#8caaee",
			TokenPanelBg:     "#292c3c",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#303446",
			TokenSelectionBg: "#414559",
			TokenSurface0:    "#414559",
			TokenSurface1:    "#51576d",
			TokenSurfaceDim:  "#303446",
			TokenOverlay0:    "#737994",
			TokenOverlay1:    "#838ba7",
			TokenText:        "#c6d0f5",
			TokenSubtext0:    "#a5adce",
			TokenMauve:       "#ca9ee6",
			TokenGreen:       "#a6d189",
			TokenYellow:      "#e5c890",
			TokenRed:         "#e78284",
			TokenBlue:        "#8caaee",
			TokenTeal:        "#81c8be",
			TokenPeach:       "#ef9f76",
		},
	},
	{
		// Catppuccin Macchiato, mapped like Herdr's Catppuccin Mocha (shep addition).
		name: "catppuccin-macchiato",
		colors: [numTokens]string{
			TokenAccent:      "#8aadf4",
			TokenPanelBg:     "#1e2030",
			TokenSidebarBg:   "reset",
			TokenActiveRowBg: "#24273a",
			TokenSelectionBg: "#363a4f",
			TokenSurface0:    "#363a4f",
			TokenSurface1:    "#494d64",
			TokenSurfaceDim:  "#24273a",
			TokenOverlay0:    "#6e738d",
			TokenOverlay1:    "#8087a2",
			TokenText:        "#cad3f5",
			TokenSubtext0:    "#a5adcb",
			TokenMauve:       "#c6a0f6",
			TokenGreen:       "#a6da95",
			TokenYellow:      "#eed49f",
			TokenRed:         "#ed8796",
			TokenBlue:        "#8aadf4",
			TokenTeal:        "#8bd5ca",
			TokenPeach:       "#f5a97f",
		},
	},
}
